/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'checkin' : string,
  'stayName' : string,
  'createdAt' : bigint,
  'guestName' : string,
  'email' : string,
  'checkout' : string,
  'phone' : string,
  'guests' : bigint,
  'location' : string,
}
export interface Category { 'name' : string, 'description' : string }
export interface _SERVICE {
  'addCategory' : ActorMethod<[string, string], undefined>,
  'createBooking' : ActorMethod<
    [string, string, string, string, string, string, string, bigint],
    Booking
  >,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getBooking' : ActorMethod<[string], Booking>,
  'getCategory' : ActorMethod<[string], Category>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];