/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'status' : string,
  'checkin' : string,
  'stayName' : string,
  'createdAt' : bigint,
  'propertyId' : string,
  'guestName' : string,
  'email' : string,
  'checkout' : string,
  'phone' : string,
  'guests' : bigint,
  'location' : string,
}
export interface Customer {
  'active' : boolean,
  'password' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface HotelOwner {
  'active' : boolean,
  'password' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface Property {
  'id' : string,
  'ownerEmail' : string,
  'status' : string,
  'propertyName' : string,
  'propertyType' : string,
  'imageUrls' : Array<string>,
  'checkinTime' : string,
  'city' : string,
  'pricePerNight' : bigint,
  'description' : string,
  'amenities' : Array<string>,
  'address' : string,
  'rules' : string,
  'checkoutTime' : string,
  'contactPhone' : string,
}
export interface UserProfile {
  'userType' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveProperty' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [string, string, string, string, string, string, string, string, bigint],
    Booking
  >,
  'deleteBooking' : ActorMethod<[string], undefined>,
  'deleteCustomer' : ActorMethod<[string], undefined>,
  'deleteOwner' : ActorMethod<[string], undefined>,
  'deleteProperty' : ActorMethod<[string], undefined>,
  'disableCustomer' : ActorMethod<[string], undefined>,
  'disableOwner' : ActorMethod<[string], undefined>,
  'enableCustomer' : ActorMethod<[string], undefined>,
  'enableOwner' : ActorMethod<[string], undefined>,
  'getAllApprovedProperties' : ActorMethod<[], Array<Property>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllOwners' : ActorMethod<[], Array<HotelOwner>>,
  'getAllPendingProperties' : ActorMethod<[], Array<Property>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getBookingById' : ActorMethod<[string], Booking>,
  'getBookingsByCustomerEmail' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByPropertyId' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerByEmail' : ActorMethod<[string], Customer>,
  'getPropertiesByOwner' : ActorMethod<[string], Array<Property>>,
  'getPropertyById' : ActorMethod<[string], Property>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginCustomer' : ActorMethod<[string, string], Customer>,
  'loginOwner' : ActorMethod<[string, string], HotelOwner>,
  'registerCustomer' : ActorMethod<[string, string, string, string], Customer>,
  'registerOwner' : ActorMethod<[string, string, string, string], HotelOwner>,
  'rejectProperty' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitProperty' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      bigint,
      Array<string>,
      string,
      string,
      string,
      string,
    ],
    Property
  >,
  'updateBookingStatus' : ActorMethod<[string, string], undefined>,
  'updateCustomerPassword' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];